# Generated by Django 5.1 on 2024-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Amenaza')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='fa-solid fa-exclamation-triangle', max_length=100, null=True, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo de Detección de Amenaza',
                'verbose_name_plural': 'Modelos de Detección de Amenazas',
            },
        ),
    ]
