# Generated by Django 5.1 on 2024-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Amenaza')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('icon', models.CharField(max_length=100, verbose_name='Ícono')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
