# Generated by Django 5.1 on 2024-08-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Amenaza'),
        ),
    ]
