# Generated by Django 5.1 on 2024-09-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_management', '0002_alter_detection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name': 'Modelo de Detección de Amenaza', 'verbose_name_plural': 'Modelos de Detección de Amenazas'},
        ),
        migrations.AlterField(
            model_name='detection',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-exclamation-triangle', max_length=100, null=True, verbose_name='Ícono'),
        ),
    ]
