# Generated by Django 5.1 on 2024-09-08 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threat_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='alarms/', verbose_name='Archivo de Alarma')),
                ('notification_message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Mensaje de Notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threat_management.detection', verbose_name='Amenaza a Detectar')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
            },
        ),
    ]
