# Generated by Django 5.1 on 2024-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='last_activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última activación'),
        ),
    ]
