# Generated by Django 5.1 on 2024-09-12 02:50

import app.security.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_user_dni_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=13, unique=True, validators=[app.security.utils.validate_dni], verbose_name='DNI'),
        ),
    ]
