# Generated by Django 5.1 on 2024-09-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/default_user.jpg', max_length=1024, null=True, upload_to='users/', verbose_name='Archivo de Imagen'),
        ),
    ]
