# Generated by Django 5.1 on 2024-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threat_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('detection_models', models.ManyToManyField(blank=True, to='threat_management.detection', verbose_name='Modelos de Detección')),
            ],
            options={
                'verbose_name': 'Sesión de Monitoreo',
                'verbose_name_plural': 'Sesiones de Monitoreo',
            },
        ),
    ]
