# Generated by Django 5.1 on 2024-09-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='monitoringsession',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
