# Generated by Django 5.1 on 2024-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_monitoringsession_crowding_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsession',
            name='crowding_threshold',
            field=models.IntegerField(default=10, help_text='Número de personas a partir del cual se considera aglomeración', verbose_name='Umbral de Aglomeración'),
        ),
    ]
